{
  "components": {
    "schemas": {
      "HTTPValidationError": {
        "properties": {
          "detail": {
            "items": {
              "$ref": "#/components/schemas/ValidationError"
            },
            "title": "Detail",
            "type": "array"
          }
        },
        "title": "HTTPValidationError",
        "type": "object"
      },
      "ValidationError": {
        "properties": {
          "loc": {
            "items": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "integer"
                }
              ]
            },
            "title": "Location",
            "type": "array"
          },
          "msg": {
            "title": "Message",
            "type": "string"
          },
          "type": {
            "title": "Error Type",
            "type": "string"
          }
        },
        "required": [
          "loc",
          "msg",
          "type"
        ],
        "title": "ValidationError",
        "type": "object"
      }
    }
  },
  "info": {
    "description": "A plugin for ChatGPT that parses Windows event logs for analysis.",
    "servers": [
      "http://localhost:9001"
    ],
    "title": "ChatGPT Event Reader Plugin",
    "version": "0.1.1"
  },
  "openapi": "3.0.2",
  "paths": {
    "/api/v1/evtx/evtx-parser": {
      "post": {
        "description": "Parses EVTX files provided by the user.",
        "operationId": "evtx_parser_api_api_v1_evtx_evtx_parser_post",
        "parameters": [
          {
            "in": "query",
            "name": "evtx_path",
            "required": true,
            "schema": {
              "title": "Evtx Path",
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "timestamp_start",
            "required": true,
            "schema": {
              "title": "Timestamp Start"
            }
          },
          {
            "in": "query",
            "name": "timestamp_end",
            "required": true,
            "schema": {
              "title": "Timestamp End"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "items": {},
                  "title": "Response Evtx Parser Api Api V1 Evtx Evtx Parser Post",
                  "type": "array"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "summary": "Evtx Parser Api"
      }
    }
  }
}